src/components/Menu/index.tsx

* Change display cake price to srk price
pic for reference

Change display cake price to srk price

---

src/utils/index.ts

* Update fix on testnet url
> Change https://bsc-testnetbscscan.com/ to https://testnet.bscscan.com/

Bug fix on testnet url

---

.gitignore
src/connectors/index.ts
src/constants/index.ts

Mobile RPC Fix

---

package.json
yarn.lock

Update package.json
* update spark-swap-uikit 0.0.2 -> 0.0.3

Update spark-swap-uikit version 0.0.3

---

package.json
src/components/Menu/config.ts
yarn.lock

Update side menu with minimal menu items

---

src/components/CurrencyInputPanel/index.tsx
src/components/swap/SwapModalFooter.tsx
src/pages/Pool/index.tsx
src/pages/Swap/index.tsx

Ui update:
- Removed description for swap and liquidity
- Update "currency" to "token"
- Remove helper text

Feat/swap UI

---

src/assets/images/blue-loader.svg
src/components/CurrencyInputPanel/index.tsx
src/components/SearchModal/CurrencySearch.tsx
src/pages/RemoveLiquidity/index.tsx

Updated user interface
- New loader svg color
- Remove "FLIP" wording
- Remove bg music when clicking token

Clean pancake trace

---

public/index.html

Change metadata absolute link

---

package.json
public/index.html
yarn.lock

Restore dark mode and fix missing logo with sparkswap.finance URL

---

src/components/CurrencyLogo/index.tsx
src/constants/token/sparkswap.json

Add bSRK token to default list

---

public/index.html

Update Misspelled Metadata Info

---

src/components/Column/index.tsx
src/components/CurrencyInputPanel/index.tsx
src/components/Menu/config.ts
src/components/swap/styleds.tsx
src/pages/AddLiquidity/PoolPriceBar.tsx
src/pages/AddLiquidity/index.tsx
src/pages/Swap/index.tsx

Minor patches #2
* Add Help to links
* Update mobile view to include tablets

Minor issues

---

src/components/TransactionConfirmationModal/TransactionSubmittedContent.tsx
src/pages/AddLiquidity/index.tsx

Change decimal from 3 to 15

---

src/components/Popups/PopupItem.tsx
src/components/Popups/TransactionPopup.tsx
src/components/Popups/index.tsx
src/components/TransactionConfirmationModal/TransactionConfirmationModal.tsx
src/components/TransactionConfirmationModal/TransactionSubmittedContent.tsx
src/pages/App.tsx

Changes: 
✅ Add transaction notification

Add notification for transactions

---

src/components/PositionCard/index.tsx
src/pages/AddLiquidity/index.tsx
src/pages/AddLiquidity/redirects.tsx
src/pages/App.tsx
src/pages/Pool/index.tsx
src/pages/PoolFinder/index.tsx
src/pages/RemoveLiquidity/redirects.tsx

Fix missing active link indicator for some components

---

src/pages/App.tsx

Merge the develop branch to the master branch, preparation to v2.1.0 

---

src/pages/Banner.tsx

Set banners as link to **AIRDROP**
_Cant provide screenshots, see code_

Add link to banner

---

package.json
yarn.lock

Apply uikit update icons and link:

Update uikit to v1.0.11

---

src/components/PageHeader/SettingsModal.tsx
src/components/PageHeader/TransactionDeadlineSetting.tsx
src/pages/Swap/index.tsx

Swap component ui fix

---

package.json
src/components/PageHeader/SettingsModal.tsx
yarn.lock

✅Update uikit version 1.0.12
✅Remove unwanted border color

Update build and minor ui bug fix

---

src/pages/Banner.tsx

Remove unwanted border

---

src/pages/Swap/index.tsx

Fix alignment - Approve and Swap Buttons

---

src/pages/Swap/index.tsx

fix button margins

---

src/components/Menu/config.ts

Add link to SparkLaunch App

---

src/components/CardNav/index.tsx
src/components/NavigationTabs/index.tsx

Modify component to remove the warning 
( except dyan sa api warning for translation yan di naman natin ginamit yan )

Fix cardnav property warning

---

src/components/Menu/config.ts
src/pages/App.tsx

Add link to teams

---

public/index.html

Fix meta content typo

---

src/components/PageHeader/SettingsModal.tsx
src/components/PageHeader/index.tsx

Add slippage tolerance settings on Add Liquidity tab

---

src/pages/Swap/index.tsx
src/state/swap/hooks.ts

Add srkb as default output token

---

src/pages/Banner.tsx

Update airdrop banner link

---

package.json
src/components/Menu/index.tsx
src/pages/App.tsx
yarn.lock

closes #115 
Updates: 
* Disable dark option
* Remove unnecessary copyright title
* Update uikit -> v1.2.9

Update packages and disable dark option

---

package.json
src/components/CurrencyInputPanel/index.tsx
yarn.lock

Add LOADING component for amount values when connecting

---

package.json
src/connectors/index.ts
yarn.lock

Upgrade to stable version 
closes #120

Update packages and wallet connect

---

src/pages/Website/components/styles/Layout/index.tsx

[style] remove red border component guide

---

src/pages/Website/components/Footer/SocialGroup.tsx
src/pages/Website/components/Footer/config.ts
src/pages/Website/components/Footer/styled.ts

Update footer launch button design

---

src/pages/Website/components/Team/index.tsx

Fix team section view on mobile

---

src/pages/Website/components/Exchanges/index.tsx

Resolves #153 
Resolves #154 
@swengr-janan may api pala ginamit dito dati. tig hardcode ko na muna ta ma deploy na sa live ngunyan. ayuson ko din api duman ta iba na si inot na company tas link

[fix] exchanges links and typo

---

src/pages/Website/components/Navigation/NavbarMenu.tsx
src/pages/Website/components/Navigation/config.ts
src/pages/Website/components/Team/index.tsx

Closes #158 
References CR https://github.com/sparkpointio/spark-swap-interface/pull/151#pullrequestreview-989161555
Before:
After:

Redirect whitepaper nav menu link to open in new tab

---

src/pages/Website/components/Navigation/MenuLink.tsx
src/pages/Website/components/Navigation/NavbarMenu.tsx

Refactor menu link target blank

---

src/components/Menu/config.ts

Update bridge nav menu route

---

src/pages/Website/components/SupportedCrypto/index.tsx

remove xdai

---

src/components/Menu/config.ts

Update farms and pools nav menu route

---

src/pages/Website/components/Footer/config.ts
src/pages/Website/components/Footer/index.tsx

Closes #165 
Closes #171 
Before:
After:

Update footer menu item and style

---

src/pages/Website/components/Exchanges/index.tsx
src/pages/Website/components/KeyFeatures/index.tsx
src/pages/Website/components/SfuelToken/index.tsx

closes #157 
closes #167 
closes #168

[style] style issues/bug and update new content

---

src/pages/Website/components/Newsletter/SignUp.tsx

Fix newsletter margins on mobile

---

src/pages/App.tsx
src/pages/Website/components/Footer/config.ts
src/pages/Website/components/Navigation/config.ts

Route fix for Sparkswap homepage and App

---

package.json
src/pages/App.tsx
src/pages/SparkSwapWebsite/components/Hero/index.tsx
yarn.lock

Redirect hero launch button to swap

---

src/pages/SparkSwapWebsite/components/Footer/SocialGroup.tsx
src/pages/SparkSwapWebsite/components/Footer/index.tsx
src/pages/SparkSwapWebsite/components/Footer/styled.ts
src/pages/SparkSwapWebsite/components/Hero/index.tsx

Closes #188 
Before:
After:
Before:
After:

Website footer mobile responsiveness and update footer styles

---

src/pages/SparkSwapWebsite/components/Hero/index.tsx

Adjust hero svg

---

src/pages/SparkSwapWebsite/components/Navigation/styled.ts

Change spacing format

---

src/pages/SparkSwapWebsite/components/Unlock/Unlock.tsx

Fix missing PavingFinTech image

---

src/pages/SparkSwapWebsite/components/Elements/Title/index.tsx
src/pages/SparkSwapWebsite/components/Exchanges/Exchanges.tsx
src/pages/SparkSwapWebsite/components/Hero/Hero.tsx
src/pages/SparkSwapWebsite/components/OnlineCommunities/OnlineCommunities.tsx
src/pages/SparkSwapWebsite/components/Team/Team.tsx
src/pages/SparkSwapWebsite/components/Unlock/Unlock.tsx

ALSO
RESOLVES #237 
RESOLVS #246 
desktop:
mobile:

[style] temporary code for responsive fix

---

src/pages/SparkSwapWebsite/components/Hero/Hero.tsx
src/pages/SparkSwapWebsite/components/Platform/Platform.tsx
src/pages/SparkSwapWebsite/components/Platform/config.ts
src/pages/SparkSwapWebsite/components/Platform/types.ts

Closes #231
Closes #244 
Closes #248 
Hero before:
Hero after:
Platform:

Hero and platform enhancements

---

src/pages/SparkSwapWebsite/components/Contact/Form.tsx
src/pages/SparkSwapWebsite/components/Contact/type.ts

[feat] contact - add receiver and sent status

---

src/pages/SparkSwapWebsite/components/Hero/Hero.tsx
src/pages/SparkSwapWebsite/components/Hero/types.ts
src/pages/SparkSwapWebsite/components/Team/Team.tsx

Refactor coming up list, upnext list updates, and fix  teams' styled hr  

---

public/index.html

closes https://github.com/sparkpointio/spark-swap-interface/issues/256, https://github.com/sparkpointio/spark-swap-interface/issues/257

Update gtag scripts to support GA4

---

src/pages/SparkSwapWebsite/components/Footer/Footer.tsx
src/pages/SparkSwapWebsite/components/Footer/styled.ts
src/pages/SparkSwapWebsite/components/Hero/Hero.tsx

Fix footer margins, footer style, and hero updates

---

src/pages/SparkSwapWebsite/components/Elements/Tab/styled.tsx
src/pages/SparkSwapWebsite/components/Roadmap/Roadmap.tsx
src/pages/SparkSwapWebsite/config/constants/Roadmap.ts
src/pages/SparkSwapWebsite/config/constants/types.ts

closes #267 
* Update roadmap placeholder
* Update roadmap configs

Roadmap updates remove months

---

src/pages/SparkSwapWebsite/components/Navigation/Navigation.tsx
src/pages/SparkSwapWebsite/components/Navigation/PanelBody.tsx
src/pages/SparkSwapWebsite/components/Navigation/PanelFooter.tsx

* Add launch button 
* Fix missing logo icon on footer
closes #264

Navbar updates

---

src/pages/SparkSwapWebsite/components/Exchanges/Exchanges.tsx
src/pages/SparkSwapWebsite/components/Footer/Footer.tsx

Closes #262
Closes #195
Closes #276
Closes #252

Fix overflow of items and mobile style updates

---

src/pages/SparkSwapWebsite/components/Roadmap/Roadmap.tsx
src/pages/SparkSwapWebsite/components/Roadmap/styled.ts
src/pages/SparkSwapWebsite/config/constants/Roadmap.ts
src/pages/SparkSwapWebsite/config/constants/types.ts

Added 2023 onwards roadmap details

Integrate more roadmap information

---

src/pages/SparkSwapWebsite/components/Roadmap/Roadmap.tsx

set roadmap default `all` section
Closes #281

Update Roadmap section

---

package.json
src/Providers.tsx
src/components/ToastListener/index.tsx
src/contexts/ToastsContext/Provider.tsx
src/contexts/ToastsContext/index.tsx
src/contexts/ToastsContext/types.ts
src/hooks/useToast.ts
src/pages/App.tsx
src/pages/SparkSwapWebsite/components/Contact/Form.tsx
yarn.lock

Update contact and add toast notif

---

src/pages/SparkSwapWebsite/components/Footer/styled.ts
src/pages/SparkSwapWebsite/components/Navigation/MenuEntry.tsx

Closes #285 
Before: 
After:
Before:
After:

Update navigation and footer active theme colors

---

src/pages/SparkSwapWebsite/components/Footer/Footer.tsx
src/pages/SparkSwapWebsite/components/Footer/styled.ts
src/pages/SparkSwapWebsite/components/styles/Layout/Breakpoints.ts

center elements

---

.env.test
.github/workflows/tests.yaml
cypress/integration/add-liquidity.test.ts
cypress/integration/landing.test.ts
cypress/integration/pool.test.ts
cypress/integration/remove-liquidity.test.ts
package.json
src/components/CardNav/index.tsx
src/components/CurrencyInputPanel/index.tsx
src/components/Menu/config.ts
src/components/NavigationTabs/index.tsx
src/constants/index.ts
src/constants/token/sparkswap.json
src/pages/AddLiquidity/redirects.tsx
src/pages/App.tsx
src/pages/DappsBanner.tsx
src/pages/MigrateV1/index.tsx
src/utils/prices.test.ts
yarn.lock

Enable cypress and other unit tests

Fix unit tests

---

src/pages/SparkSwapWebsite/components/Hero/Hero.tsx

- Closes #304 
- Minor adjustments on carousel custom styled link
Before:
After:

Update custom styled link style and adjust volume container 
